logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.189.128 #主机名
    port: 5672 #端口
    virtual-host: / #虚拟机
    username: itcast #用户名
    password: 101104 #密码

